modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

authors="${mod_authors}"

description='''${mod_description}'''

[[mixins]]
config="create_bic_bit.mixins.json"

[[dependencies.create_bic_bit]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.create_bic_bit]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_bic_bit]]
modId="create"
type="required"
versionRange="[6.0.8,6.1.0)"
ordering="NONE"
side="BOTH"

